/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_nodes"];
        put?: never;
        post: operations["create_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_node"];
        put?: never;
        post?: never;
        delete: operations["delete_node"];
        options?: never;
        head?: never;
        patch: operations["update_node"];
        trace?: never;
    };
    "/api/v1/nodes/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为 node 签发运行时凭据（§5/§71）。明文 token 仅此一次返回。 */
        post: operations["create_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}/credentials/{credential_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销凭据（§71）：写 `revoked_at`，之后 Agent 无法认证。 */
        post: operations["revoke_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_routes"];
        put?: never;
        post: operations["create_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_route"];
        put?: never;
        post?: never;
        delete: operations["delete_route"];
        options?: never;
        head?: never;
        patch: operations["update_route"];
        trace?: never;
    };
    "/api/v1/routes/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disable_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enable_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询是否已初始化（`users` 表是否为空）。 */
        get: operations["setup_status"];
        put?: never;
        /** 创建初始管理员：仅当系统尚无任何用户时可用；成功后直接签发会话（登录态）。 */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录：校验密码 → 建会话 → 设 cookie + 返回短时 token；错误凭据 401。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出：吊销会话并清 cookie（幂等，未登录也返回 204）。 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户：cookie 或 Bearer token 任一有效即返回。 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新：校验 cookie 会话后签发新短时访问 token。 */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCredentialRequest: {
            expires_at?: string | null;
            type?: string;
        };
        CreateNodeRequest: {
            description?: string | null;
            name: string;
        };
        /** @description 创建 Node 的响应：`node` + 一次性 bootstrap token（明文仅此一次，§4/§94）。 */
        CreateNodeResponse: {
            bootstrap_token: string;
            node: components["schemas"]["Node"];
        };
        CreateRouteRequest: {
            enabled?: boolean;
            hostname?: string | null;
            limits?: components["schemas"]["Limits"] | null;
            listen_host?: string | null;
            /** Format: int32 */
            listen_port?: number | null;
            name: string;
            node_id: string;
            target_host: string;
            /** Format: int32 */
            target_port: number;
            tls_mode?: components["schemas"]["TlsMode"] | null;
            type: components["schemas"]["RouteType"];
        };
        /** @description 新凭据响应：`token` 为明文，仅创建时返回一次（§71）。 */
        CredentialResponse: {
            id: string;
            token: string;
        };
        EnrollRequest: {
            agent_version?: string | null;
            architecture?: string | null;
            bootstrap_token: string;
            hostname?: string | null;
            node_name?: string | null;
            platform?: string | null;
        };
        EnrollResponse: {
            /** Format: int64 */
            config_version: number;
            credential: string;
            node_id: string;
        };
        Limits: {
            /** Format: int64 */
            max_bandwidth?: number | null;
            /** Format: int64 */
            max_connection_rate?: number | null;
            /** Format: int64 */
            max_connections?: number | null;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            access_token: string;
            token_type: string;
            user: components["schemas"]["User"];
        };
        MeResponse: {
            user: components["schemas"]["User"];
        };
        /** @description Node 响应对象（api.md §5）。 */
        Node: {
            agent_version?: string | null;
            /** Format: int64 */
            applied_config_version: number;
            architecture?: string | null;
            config_status: string;
            /** Format: int64 */
            config_version: number;
            connected_at?: string | null;
            description?: string | null;
            hostname?: string | null;
            id: string;
            last_seen_at?: string | null;
            name: string;
            platform?: string | null;
            remote_addr?: string | null;
            status: string;
        };
        RefreshResponse: {
            access_token: string;
            token_type: string;
        };
        /** @description Route 响应对象（api.md §6）。 */
        Route: {
            enabled: boolean;
            hostname?: string | null;
            id: string;
            limits?: components["schemas"]["Limits"] | null;
            listen_host?: string | null;
            /** Format: int32 */
            listen_port?: number | null;
            name: string;
            node_id: string;
            status: string;
            target_host: string;
            /** Format: int32 */
            target_port: number;
            tls_mode?: string | null;
            type: components["schemas"]["RouteType"];
        };
        /** @enum {string} */
        RouteType: "tcp" | "udp" | "http" | "https";
        SetupRequest: {
            email?: string | null;
            password: string;
            username: string;
        };
        SetupStatusResponse: {
            initialized: boolean;
        };
        /** @enum {string} */
        TlsMode: "terminate" | "passthrough" | "disabled";
        UpdateNodeRequest: {
            description?: string | null;
            name?: string | null;
        };
        UpdateRouteRequest: {
            enabled?: boolean | null;
            hostname?: string | null;
            limits?: components["schemas"]["Limits"] | null;
            listen_host?: string | null;
            /** Format: int32 */
            listen_port?: number | null;
            name?: string | null;
            node_id?: string | null;
            target_host?: string | null;
            /** Format: int32 */
            target_port?: number | null;
            tls_mode?: components["schemas"]["TlsMode"] | null;
            type?: components["schemas"]["RouteType"] | null;
        };
        /** @description 已登录用户（下发 /auth/me 与登录响应的最小画像）。 */
        User: {
            email?: string | null;
            id: string;
            role: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
        };
    };
    create_node: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeRequest"];
            };
        };
        responses: {
            /** @description Node created (bootstrap token shown once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateNodeResponse"];
                };
            };
            /** @description Duplicate name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodeRequest"];
            };
        };
        responses: {
            /** @description Node updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Credential created (token shown once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node id */
                id: string;
                /** @description Credential id */
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credential not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_routes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List routes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"][];
                };
            };
        };
    };
    create_route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRouteRequest"];
            };
        };
        responses: {
            /** @description Route created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate name/listen/hostname */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRouteRequest"];
            };
        };
        responses: {
            /** @description Route updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disable_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enable_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Initial admin created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Setup already done */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid username/password */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many failed attempts (locked) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled; runtime credential shown once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            /** @description Invalid or used bootstrap token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description node_name mismatch or empty token */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
